### ISSUE TITLE
Allow script to be run with dropped privileges

### ISSUE THREAD

**Issue by brunnre8** [jonathanio/update-systemd-resolved#26]
Is there an option to run the script with dropped privileges as a specific user?

In case that's trivially doable please excuse my ignorance, but I could not find a way.

Could the script be adapted to work without root?
In principle the call to `busctl` could be wrapped in a sudo call yes?  
Then we could add an  unprivileged user to the /etc/sudoers file with this specific command.

Do you plan on supporting that?

**Comment by brunnre8** [comment]
I found a (very) hacky solution...
One can use the openvpn-plugin-down-root.so that comes with the openvpn package, however due to a [bug in the plugin](https://community.openvpn.net/openvpn/ticket/338) one has to provide the `script_type` and `dev` environment variables to the `update-systemd-resolved` script

In the client.conf add the following:
```bash
script-security 2
setenv PATH /usr/bin
up /etc/openvpn/update-systemd-resolved
plugin /usr/lib/openvpn/plugins/openvpn-plugin-down-root.so "/etc/openvpn/update-systemd-resolved.down"
down-pre
```

And `etc/openvpn/update-systemd-resolved.down` (of couse modify the device accordingly to your needs)
```bash
#!/usr/bin/env bash
script_type=down  dev=tun1 /etc/openvpn/update-systemd-resolved
```

Is there a better way?

**Comment by jonathanio** [comment]
It is something I have considered, but that this time the issues involved in trying to ensure it runs, DBUS permissions, etc. outweighed the benefits to me.

The script is not a long-running one and simply makes changes to the system briefly before exiting. If you're running under dropped privileges for `openvpn`, it only drops after setup and the script cannot work because it doesn't have permissions to run some commands (there's a check in there to detect when it's not run as `root` to avoid breaking `openvpn`.

The fact that all scripts of this nature in the past have always required `root` privileges to run because they either needed to directly edit or manage `/etc/resolv.conf` or the `systemd-networkd` unit files does not mean that mine should require `root` always and I'm open to suggestions on how to enable this.

I suspect it will need to be a three-pronged attack:

- What configuration is required in `openvpn` to enable dropped privileges on `up` as well as `down` states;
- What configuration is required by DBUS to allow non-root or selected accounts/groups permission to communicate with, and update, `systemd-resolved.service`; and
- Any relevant changes in `update-systemd-resolved` to support this dual-mode of configuration (possible a test command to see if permissions are available?).

I'm open to suggestions myself, although nothing personally comes to mind. `sudo` could be an option, but you need to be careful about cases where `sudo` is not present on a system and handle when you cannot use it.

**Comment by rkraneis** [comment]
Regarding @brunnre8 comment: for me the down-root-plugin solution does not really work (at least on ubuntu 17.10; it worked on ubuntu 16.04 when we could still change the resolv.conf directly):

```
^CMon Nov  6 12:04:37 2017 event_wait : Interrupted system call (code=4)
Mon Nov  6 12:04:37 2017 /sbin/ip route del x.y.1.0/24
RTNETLINK answers: Operation not permitted
Mon Nov  6 12:04:37 2017 ERROR: Linux route delete command failed: external program exited with error status: 2
Mon Nov  6 12:04:37 2017 /sbin/ip route del x.z.0.1/32
RTNETLINK answers: Operation not permitted
Mon Nov  6 12:04:37 2017 ERROR: Linux route delete command failed: external program exited with error status: 2
<14>Nov  6 12:04:37 update-systemd-resolved: Link 'tun0' going down
Mon Nov  6 12:04:37 2017 PLUGIN_CALL: POST /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-down-root.so/PLUGIN_DOWN status=0
Mon Nov  6 12:04:37 2017 Closing TUN/TAP interface
Mon Nov  6 12:04:37 2017 /sbin/ip addr del dev tun0 local x.z.0.10 peer x.y.0.9
RTNETLINK answers: Operation not permitted
Mon Nov  6 12:04:37 2017 Linux ip addr del failed: external program exited with error status: 2
Mon Nov  6 12:04:37 2017 PLUGIN_CLOSE: /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-down-root.so
Mon Nov  6 12:04:37 2017 SIGINT[hard,] received, process exiting
```

**Comment by jonathanio** [comment]
I've added some details to the `README.md` document about trying to use the plugin to enable running `down` as root. It is something that is outside the script of this script and is a limitation within `systemd-resolved` and the choice of configuration by the user.

I prefer to enable `user` (and potentially `group`) in the configuration and not care if `down` is run or not. `systemd-resolved.service` will automatically update everything when the `tun` or `tap` device is removed - including the `/etc/resolv.conf` script - so the system just becomes reactive rather than being explicitly told to remove the configuration for the device as it's being torn down.

**Comment by fieldawarepiotr** [comment]
without `setenv PATH /usr/bin` I didn't have the issue.
