### ISSUE TITLE
dnssec

### ISSUE THREAD

**Issue by joksik** [jonathanio/update-systemd-resolved#52]
hello, i use your script quite long time. I've never had a problem with it. i use nordvpn under arch linux. from few days something was wrong because i dont have internet so i switch to windows and see that nordvpn servers works fine. after i uninstall your script i can connect to internet with my nordvpn so somethings after latest arch updates was wrong. i suspect latest update for systemd may cause this bug because the same errors i found in arch board:
https://bbs.archlinux.org/viewtopic.php?id=240427

in /etc/resolv.conf i have this entry
hosts: files resolve myhostname

and when i check status for 
systemctl status systemd-resolved.service
i have many errors with DNSSEC validation failed

after few hours of testing what its wrong i figure out that i must edit
sudo nano /etc/systemd/resolved.conf
and change from
#DNSSEC=allow-downgrade
 to
DNSSEC=no

after this change i can still use your script and i have internet when i connect to nordvpn but maybe 
you know something more why it stops working ? or you must update your script for new systemd release?

**Comment by jonathanio** [comment]
@joksik,

It's an interesting one, but as far as I can see, NordVPN doesn't support DNSSEC. Any references to it show it unchecked or disabled. The other side of the coin in that regard could be that they've made a configuration change on their own servers which disable or ignore DNSSEC records.

When you're connecting in Windows, have you run a DNSSEC check to verify that you are receiving and processing DNSSEC records?

**Comment by joksik** [comment]
now when you write to check DNSSEC it`s quite interesting because under arch where i disable dnssec and under windows where i download for test new config from nordvpn i visit this two sites for test:
https://dnssec.vs.uni-due.de/
http://en.conn.internet.nl/connection/
and both test say that i use dnssec ;)

**Comment by jonathanio** [comment]
The Root Key Signing Key is being rotated on October 11. The new one is already in place, and the old one is deprecated and will be removed on October 11. I wonder if there is an issue with the key's `systemd-resolved` is using?

**Comment by jstephenson** [comment]
I was having difficulty too, and as OP suspects I believe it's because Arch was disabling DNSSEC support at build-time until systemd 239.2 (see https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/systemd&id=eb4a95338add2fadb10caa64fb1d811989431f57 for the change).

After this change I could see with `resolvectl` that the VPN iface was marked as supporting DNSSEC regardless of my efforts to disable it at the DNS server and/or with pushed `dhcp-options` etc. The only 'fix' I could find without spending time researching was to simply disable DNSSEC in `/etc/systemd/resolved.conf`. Perhaps there's an issue with capability detection, perhaps I am missing something ‒ time will no doubt tell!

**Comment by jonathanio** [comment]
Actually, this goes beyond VPNs. I've noticed some unusual DNS activity recently even when not connected to a VPN with DNS resolution. DNSSEC validation seems to fail when you're connected to routers that don't fully support the standard and are unable provide enough information for `allow-downgrade` to work as per the new default setting (at least on Arch Linux). For example:

``` bash
$ systemd-resolve eu-central-1.console.aws.amazon.com
eu-central-1.console.aws.amazon.com: resolve call failed: DNSSEC validation failed: no-signature
```

That resolution as made over a wired network to the office router's DNS resolver. In this case, I had to set `DNSSEC=no` in the `.network` file for `systemd-networkd.service`.

**Comment by Edu4rdSHL** [comment]
@jonathanio please don't change  DNSSEC to  DNSSEC=no, DNSSEC stuff should be fixed by the user and not by the script. The script is doing well the work.

**Comment by jonathanio** [comment]
@Edu4rdSHL agreed. Default settings should be left to the end user, and the script should only be used to override these defaults when explicitly let. Unless a valid `dhcp-option` is passed into the script, this script will do nothing and return with an `exit 0`, and I think it should be kept this way.

As this is a general issue with the changes in the configuration of systemd within Arch, I'll close this as it's not something I can directly fix. Nonetheless, I've added some documentation on what to do when you see issues with DNS resolutions due to DNSSEC failures.
